language: python
python:
    - 3.5

install:
    - pip install --upgrade pipenv
    - pipenv install --three --dev
    - pipenv uninstall django 
    - pipenv install django==1.8.18 

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - pipenv run coverage run -m pytest

after_sucess:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t coverage.py
